stages:
  - tag
  - build

tag_project:
  stage: tag
  script:
    - semantic-release
    - mvn versions:set -DnewVersion=$(git describe --tags --abbrev=0)

build_project:
  stage: build
  script: mvn clean compile install

