stages:
  - tag
  - build

tag_project:
  stage: tag
  script: semantic-release

build_project:
  stage: build
  script: mvn versions:set -DnewVersion=$(git describe --tags --abbrev=0) clean compile package

